f = open('C:/Users/aleja/agente_secop/agente_secop.py', 'w', encoding='utf-8')
f.write("import anthropic\n")
f.write("import requests\n")
f.write("import json\n")
f.write("from datetime import datetime\n")
f.write("from config_legacy import API_KEY, DEPARTAMENTO, VALOR_MINIMO, MAX_LICITACIONES, KEYWORDS_HVAC, ARCHIVO_ENVIADOS\n\n")
f.write("client = anthropic.Anthropic(api_key=API_KEY)\n\n")
f.write("def cargar_enviados():\n")
f.write("    with open(ARCHIVO_ENVIADOS, 'r') as arch:\n")
f.write("        return json.load(arch)['enviados']\n\n")
f.write("def guardar_enviado(codigo):\n")
f.write("    data = {'enviados': cargar_enviados()}\n")
f.write("    data['enviados'].append({'codigo': codigo, 'fecha': datetime.now().strftime('%Y-%m-%d %H:%M')})\n")
f.write("    with open(ARCHIVO_ENVIADOS, 'w') as arch:\n")
f.write("        json.dump(data, arch, ensure_ascii=False, indent=2)\n\n")
f.write("def ya_fue_enviado(codigo):\n")
f.write("    enviados = cargar_enviados()\n")
f.write("    return any(e['codigo'] == codigo for e in enviados)\n\n")
f.write("def buscar_licitaciones():\n")
f.write("    print('Buscando licitaciones en SECOP II...')\n")
f.write("    url = 'https://www.datos.gov.co/resource/p6dx-8zbt.json'\n")
f.write("    params = {'$where': \"fecha_de_publicacion > '2026-01-01T00:00:00' AND estado_del_procedimiento = 'Publicado'\", '$limit': '50', '$order': 'fecha_de_publicacion DESC'}\n")
f.write("    try:\n")
f.write("        respuesta = requests.get(url, params=params, timeout=10)\n")
f.write("        licitaciones = respuesta.json()\n")
f.write("        print(f'Se encontraron {len(licitaciones)} licitaciones')\n")
f.write("        return licitaciones\n")
f.write("    except Exception as e:\n")
f.write("        print(f'Error: {e}')\n")
f.write("        return []\n\n")
f.write("def filtrar_por_keywords(licitaciones):\n")
f.write("    relevantes = []\n")
f.write("    for lic in licitaciones:\n")
f.write("        objeto = (lic.get('nombre_del_procedimiento', '') + ' ' + lic.get('descripci_n_del_procedimiento', '')).lower()\n")
f.write("        for keyword in KEYWORDS_HVAC:\n")
f.write("            if keyword.lower() in objeto:\n")
f.write("                relevantes.append(lic)\n")
f.write("                break\n")
f.write("    print(f'Despues keywords: {len(relevantes)} licitaciones')\n")
f.write("    return relevantes\n\n")
f.write("def filtrar_por_valor(licitaciones):\n")
f.write("    relevantes = []\n")
f.write("    for lic in licitaciones:\n")
f.write("        try:\n")
f.write("            valor = float(lic.get('precio_base', 0))\n")
f.write("            if valor >= VALOR_MINIMO:\n")
f.write("                relevantes.append(lic)\n")
f.write("        except:\n")
f.write("            relevantes.append(lic)\n")
f.write("    print(f'Despues valor: {len(relevantes)} licitaciones')\n")
f.write("    return relevantes\n\n")
f.write("def analizar_licitacion(licitacion):\n")
f.write("    objeto = licitacion.get('nombre_del_procedimiento', 'No disponible')\n")
f.write("    descripcion = licitacion.get('descripci_n_del_procedimiento', 'No disponible')\n")
f.write("    valor = licitacion.get('precio_base', 'No disponible')\n")
f.write("    entidad = licitacion.get('entidad', 'No disponible')\n")
f.write("    fecha_cierre = licitacion.get('fecha_de_recepcion_de', 'No disponible')\n")
f.write("    url = licitacion.get('urlproceso', {}).get('url', 'No disponible')\n")
f.write("    prompt = 'Eres experto en licitaciones de Colombia. Analiza para Rema-Multiservicios (HVAC, electrica, obras civiles, Neiva Huila).\\n'\n")
f.write("    prompt += f'Objeto: {objeto}\\nDescripcion: {descripcion}\\nValor: {valor}\\nEntidad: {entidad}\\nCierre: {fecha_cierre}\\n'\n")
f.write("    prompt += '{\"relevante\": true/false, \"score\": 0-100, \"motivo\": \"max 20 palabras\", \"accion\": \"PRESENTAR/REVISAR/DESCARTAR\", \"urgente\": true/false}'\n")
f.write("    try:\n")
f.write("        respuesta = client.messages.create(model='claude-sonnet-4-6', max_tokens=300, temperature=0.1, messages=[{'role': 'user', 'content': prompt}])\n")
f.write("        texto = respuesta.content[0].text.strip()\n")
f.write("        return json.loads(texto)\n")
f.write("    except Exception as e:\n")
f.write("        print(f'Error analizando: {e}')\n")
f.write("        return None\n\n")
f.write("def ejecutar_agente():\n")
f.write("    print('=' * 50)\n")
f.write("    print('AGENTE SECOP - REMA-MULTISERVICIOS')\n")
f.write("    print(datetime.now().strftime('%Y-%m-%d %H:%M'))\n")
f.write("    print('=' * 50)\n")
f.write("    licitaciones = buscar_licitaciones()\n")
f.write("    if not licitaciones:\n")
f.write("        print('No se encontraron licitaciones.')\n")
f.write("        return\n")
f.write("    licitaciones = filtrar_por_keywords(licitaciones)\n")
f.write("    if not licitaciones:\n")
f.write("        print('Ninguna paso el filtro de keywords.')\n")
f.write("        return\n")
f.write("    licitaciones = filtrar_por_valor(licitaciones)\n")
f.write("    if not licitaciones:\n")
f.write("        print('Ninguna paso el filtro de valor.')\n")
f.write("        return\n")
f.write("    print('Analizando con IA...')\n")
f.write("    resultados = []\n")
f.write("    for lic in licitaciones:\n")
f.write("        codigo = lic.get('id_del_proceso', lic.get('referencia_del_proceso', 'SIN-CODIGO'))\n")
f.write("        if ya_fue_enviado(codigo):\n")
f.write("            print(f'Ya analizada: {codigo}')\n")
f.write("            continue\n")
f.write("        print(f'Analizando: {codigo}')\n")
f.write("        analisis = analizar_licitacion(lic)\n")
f.write("        if analisis and analisis['relevante']:\n")
f.write("            resultados.append({'licitacion': lic, 'analisis': analisis, 'codigo': codigo})\n")
f.write("            guardar_enviado(codigo)\n")
f.write("    print(f'RESULTADOS: {len(resultados)} oportunidades encontradas')\n")
f.write("    if not resultados:\n")
f.write("        print('No se encontraron oportunidades relevantes.')\n")
f.write("        return\n")
f.write("    for r in resultados:\n")
f.write("        lic = r['licitacion']\n")
f.write("        analisis = r['analisis']\n")
f.write("        print('-' * 50)\n")
f.write("        print(f\"Proceso: {r['codigo']}\")\n")
f.write("        print(f\"Entidad: {lic.get('entidad', 'N/A')}\")\n")
f.write("        print(f\"Objeto: {lic.get('nombre_del_procedimiento', 'N/A')[:100]}\")\n")
f.write("        print(f\"Valor: {lic.get('precio_base', 'N/A')}\")\n")
f.write("        print(f\"Score: {analisis['score']}/100\")\n")
f.write("        print(f\"Accion: {analisis['accion']}\")\n")
f.write("        print(f\"Motivo: {analisis['motivo']}\")\n")
f.write("        print(f\"URL: {lic.get('urlproceso', {}).get('url', 'N/A')}\")\n")
f.write("\nif __name__ == '__main__':\n")
f.write("    ejecutar_agente()\n")
f.close()
print("archivo creado ok")